Stat svc
romerodeltoro/ExploreWithMe pull request #1
Opened 2023-10-06 06:41 UTC by romerodeltoro

2023-10-06 22:00 UTC, andrew-larkin requested changes
Привет! Отлично, структура выполнена корректно, остается пару правок внести и будем готовы двигаться дальше.

2023-10-06 22:00 UTC, andrew-larkin commented on stats/server/src/main/java/ru/practicum/stats/server/storage/HitRepository.java
> +    List<Object[]> findAllByTimestampWhereUrisIsNull(LocalDateTime start, LocalDateTime end);
о, почему массив object?

2023-10-06 22:00 UTC, andrew-larkin commented on stats/server/src/main/java/ru/practicum/stats/server/service/HitServiceImpl.java
> +    final DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
модификатор доступа

2023-10-06 22:00 UTC, andrew-larkin commented on stats/server/src/main/resources/application.properties
> +#spring.main.allow-bean-definition-overriding=true
закомментированный код удаляем

2023-10-07 06:45 UTC, romerodeltoro commented on stats/server/src/main/java/ru/practicum/stats/server/storage/HitRepository.java
> +    List<Object[]> findAllByTimestampWhereUrisIsNull(LocalDateTime start, LocalDateTime end);
Массив object тут по причине того, что в результате запроса будет создан столбец ( COUNT(h.ip) ) с данными, для которых у EndpointHit нет поля

2023-10-09 06:25 UTC, merged